### PR TITLE
tokssh: shared secret support,fix no user cmd line

### PR DESCRIPTION
**Pull request by fabrixxm**

### CODE REVIEW

**Comment by gjedeer** [comment]
Thanks!

**Comment by gjedeer** [comment]
Merged but in general, TUNTOX_SHARED_SECRET env variable is preferred to the -s switch.

**Comment by fabrixxm** [comment]
> in general, TUNTOX_SHARED_SECRET env variable is preferred to the -s switch.

Yup.. 
And as a "client" command line tool, better would be "-s" alone and ask user the password interactively, like ssh itself or mysql client with "-p" :-)

**Comment by gjedeer** [comment]
Good idea!

**Pull request merged**
