### PR TITLE
Improve data transfer speed and latency

### PR DESCRIPTION
**Pull request by ValdikSS**
Current version can only get 200-300 Kb/s on 1G LAN and the latency is clearly visible in ssh session.
This fix improves latency and speed by reducing sleep times and calling tox_iterate more frequently.

With this fix I get 12 Mb/s on 1G LAN. It's still far from perfect though.

### CODE REVIEW

**Comment by gjedeer** [comment]
Nice, the PR looks legit. I've had a hard time balancing speed and idle CPU usage and sent_data looks like a good idea.

Did you check that your nodes are actually communicating on a LAN and not via a relay node? toxcore does a crap job at that and I often see two nodes with public IP addresses use a relay node anyway.

**Comment by ValdikSS** [comment]
Yes I did, I removed bootstrapping for tests.
Actually there's a what I think new interface tox_loop() based on libev/libevent. It would be nice to integrate in that loop and not call iterate every time.

**Comment by gjedeer** [comment]
I did not know that. Do you have any links to information on that?

**Comment by ValdikSS** [comment]
No, it doesn't seem to be documented. I just tried it in a simple echo server and it works.

**Comment by gjedeer** [comment]
Care to put it on github or pastebin? Always better to start with an example and utox doesn't seem to use that api yet

**Comment by ValdikSS** [comment]
That's just an echo bot example from https://wiki.tox.chat/developers/client_examples/echo_bot but with `tox_loop()`
https://gist.github.com/ValdikSS/3c953e2e40761727288f2437b165536c

**Comment by gjedeer** [comment]
Thanks.

**Pull request merged**
