### PR TITLE
Add lossy mode

### PR DESCRIPTION
**Pull request by hizani**
This PR adds stateless lossy mode which is enabled by `-l` option.
Lossy mode server is compatible with lossless mode clients and vice versa.

I can't actually test it because `-L` option doesn't work in `master` build at the time the PR was created, but ping mode works fine.

### CODE REVIEW

**Comment by zoff99** [comment]
@hizani
the first byte of data for tox custom packets is the packet ID. which is globally unique.
please register all IDs here:

https://github.com/zoff99/toxcore_custom_packets_registry

thank you.

**Comment by hizani** [comment]
@zoff99 
Done. I've added only the lossless ID, because I don't know if this PR will ever be merged.

**Comment by hizani** [comment]
@gjedeer The motivation is to reduce latency caused by waiting on SENDQ [here](https://github.com/gjedeer/tuntox/blob/54289f5c94db7d8c14d228eb8dd0ba90d20c33db/main.c#L383). It can help latency-sensitive cases like device monitoring, multiplayer gaming etc.

As far as I understand it, lossy packets can work over TCP without problems but there won't be any ordering on the toxcore level.

**Comment by gjedeer** [comment]
Let me know when you test it on a lossy network and get some of [these messages](https://github.com/gjedeer/tuntox/blob/54289f5c94db7d8c14d228eb8dd0ba90d20c33db/main.c#L406) in the log. I'm pretty sure any software working over TCP will not work correctly when it loses random part of the stream. One exception I can think of is maybe some video player like mpv or vlc, these can handle completely malformed input.

**Pull request closed without merging**
