### PR TITLE
Fix some warnings and update makefile

### PR DESCRIPTION
**Pull request by Ansa89**
Now the default is to dynamically link the executable.
If you want to build a static executable use `make tuntox_static`.

### CODE REVIEW

**Comment by Ansa89** [comment]
@nCore can you try the new makefile on mac os? Hopefully you won't need a separated makefile anymore.

**Comment by gjedeer** [comment]
This doesn't build on Linux: https://zerobin.net/?3d4d41bc3381fc99#PD1jYliZQuJy1HF+cNNi6U+35nWSB8d5A5nvDvTr/28=

**Comment by gjedeer** [comment]
If you could make a commit or PR with just your changes in *.c files, I'd test and merge it. Wanted to cherry-pick commit 91d9ad27d4a7ca77c615bcf9d928f11b9d3b3c77 but it touches Makefile and Travis config.

**Comment by Ansa89** [comment]
> This doesn't build on Linux: https://zerobin.net/?3d4d41bc3381fc99#PD1jYliZQuJy1HF+cNNi6U+35nWSB8d5A5nvDvTr/28=

That's strange, I tested it on slackware 14.1 without issues and also jenkins can compile it.
What distro are you using?

**Comment by gjedeer** [comment]
Ubuntu 14.04

**Comment by Ansa89** [comment]
This is the same version as jenkins.
What is the output of `pkg-config --libs libtoxcore`?

**Comment by gjedeer** [comment]
➜  ~ pkg-config --libs libtoxcore
-L/usr/local/lib -ltoxdns -ltoxencryptsave -ltoxcore -lsodium -lm -lpthread

**Comment by Ansa89** [comment]
That seems ok.
Can you repost the error? (The paste has expired)

**Comment by gjedeer** [comment]
https://zerobin.net/?dbb6884eb22bc5d2#d2TpNKuMLtNpXX30nJGfk+Z2b2M5DeOT5hLwYmOLqiA=

It's like it doesn't find the library during linking

**Comment by Ansa89** [comment]
> It's like it doesn't find the library during linking

Yes, this is what happen, but I can't understand why.
In the makefile, try to remove the beginning `@`  from `@$(CC) $(LDFLAGS) $(OBJECTS) -o $@` in the "tuntox" target.
This should print the command executed by `make` when linking the program.

**Comment by gjedeer** [comment]
It's merged now (temporarly in "toktok-core" branch), I removed your changes which broke the build process and included the rest. Thanks!

**Pull request closed without merging**
